workflow_id: chandanbfx-scrna-seq-seurat-workflow-finish
source_cores: 8
steps:
  create_seurat_object:
    summary: create_seurat_object
    requires:
    - ../workflow_candidates/chandanbfx__scRNA-seq-Seurat-Workflow/config/config.yaml
    snakemake:
      snakefile: ../workflow_candidates/chandanbfx__scRNA-seq-Seurat-Workflow/Snakefile
      directory: ../workflow_candidates/chandanbfx__scRNA-seq-Seurat-Workflow
      use_conda: true
      cores: '{source_cores}'
      scheduler: greedy
      configfile: ../workflow_candidates/chandanbfx__scRNA-seq-Seurat-Workflow/config/config.yaml
      root_target: all
      until:
      - create_seurat_object
  qc:
    summary: qc
    requires:
    - ../workflow_candidates/chandanbfx__scRNA-seq-Seurat-Workflow/config/config.yaml
    snakemake:
      snakefile: ../workflow_candidates/chandanbfx__scRNA-seq-Seurat-Workflow/Snakefile
      directory: ../workflow_candidates/chandanbfx__scRNA-seq-Seurat-Workflow
      use_conda: true
      cores: '{source_cores}'
      scheduler: greedy
      configfile: ../workflow_candidates/chandanbfx__scRNA-seq-Seurat-Workflow/config/config.yaml
      root_target: all
      until:
      - qc
    depends_on:
    - create_seurat_object
  normalization:
    summary: normalization
    requires:
    - ../workflow_candidates/chandanbfx__scRNA-seq-Seurat-Workflow/config/config.yaml
    snakemake:
      snakefile: ../workflow_candidates/chandanbfx__scRNA-seq-Seurat-Workflow/Snakefile
      directory: ../workflow_candidates/chandanbfx__scRNA-seq-Seurat-Workflow
      use_conda: true
      cores: '{source_cores}'
      scheduler: greedy
      configfile: ../workflow_candidates/chandanbfx__scRNA-seq-Seurat-Workflow/config/config.yaml
      root_target: all
      until:
      - normalization
    depends_on:
    - qc
  batch_correction:
    summary: batch_correction
    requires:
    - ../workflow_candidates/chandanbfx__scRNA-seq-Seurat-Workflow/config/config.yaml
    snakemake:
      snakefile: ../workflow_candidates/chandanbfx__scRNA-seq-Seurat-Workflow/Snakefile
      directory: ../workflow_candidates/chandanbfx__scRNA-seq-Seurat-Workflow
      use_conda: true
      cores: '{source_cores}'
      scheduler: greedy
      configfile: ../workflow_candidates/chandanbfx__scRNA-seq-Seurat-Workflow/config/config.yaml
      root_target: all
      until:
      - batch_correction
    depends_on:
    - normalization
  dimreduction:
    summary: dimreduction
    requires:
    - ../workflow_candidates/chandanbfx__scRNA-seq-Seurat-Workflow/config/config.yaml
    snakemake:
      snakefile: ../workflow_candidates/chandanbfx__scRNA-seq-Seurat-Workflow/Snakefile
      directory: ../workflow_candidates/chandanbfx__scRNA-seq-Seurat-Workflow
      use_conda: true
      cores: '{source_cores}'
      scheduler: greedy
      configfile: ../workflow_candidates/chandanbfx__scRNA-seq-Seurat-Workflow/config/config.yaml
      root_target: all
      until:
      - dimreduction
    depends_on:
    - batch_correction
  clustering:
    summary: clustering
    requires:
    - ../workflow_candidates/chandanbfx__scRNA-seq-Seurat-Workflow/config/config.yaml
    snakemake:
      snakefile: ../workflow_candidates/chandanbfx__scRNA-seq-Seurat-Workflow/Snakefile
      directory: ../workflow_candidates/chandanbfx__scRNA-seq-Seurat-Workflow
      use_conda: true
      cores: '{source_cores}'
      scheduler: greedy
      configfile: ../workflow_candidates/chandanbfx__scRNA-seq-Seurat-Workflow/config/config.yaml
      root_target: all
      until:
      - clustering
    depends_on:
    - dimreduction
  marker_genes:
    summary: marker_genes
    requires:
    - ../workflow_candidates/chandanbfx__scRNA-seq-Seurat-Workflow/config/config.yaml
    snakemake:
      snakefile: ../workflow_candidates/chandanbfx__scRNA-seq-Seurat-Workflow/Snakefile
      directory: ../workflow_candidates/chandanbfx__scRNA-seq-Seurat-Workflow
      use_conda: true
      cores: '{source_cores}'
      scheduler: greedy
      configfile: ../workflow_candidates/chandanbfx__scRNA-seq-Seurat-Workflow/config/config.yaml
      root_target: all
      until:
      - marker_genes
    depends_on:
    - clustering
  annotation:
    summary: annotation
    requires:
    - ../workflow_candidates/chandanbfx__scRNA-seq-Seurat-Workflow/config/config.yaml
    snakemake:
      snakefile: ../workflow_candidates/chandanbfx__scRNA-seq-Seurat-Workflow/Snakefile
      directory: ../workflow_candidates/chandanbfx__scRNA-seq-Seurat-Workflow
      use_conda: true
      cores: '{source_cores}'
      scheduler: greedy
      configfile: ../workflow_candidates/chandanbfx__scRNA-seq-Seurat-Workflow/config/config.yaml
      root_target: all
      until:
      - annotation
    depends_on:
    - marker_genes
  generate_summary:
    summary: generate_summary
    requires:
    - ../workflow_candidates/chandanbfx__scRNA-seq-Seurat-Workflow/config/config.yaml
    snakemake:
      snakefile: ../workflow_candidates/chandanbfx__scRNA-seq-Seurat-Workflow/Snakefile
      directory: ../workflow_candidates/chandanbfx__scRNA-seq-Seurat-Workflow
      use_conda: true
      cores: '{source_cores}'
      scheduler: greedy
      configfile: ../workflow_candidates/chandanbfx__scRNA-seq-Seurat-Workflow/config/config.yaml
      root_target: all
      until:
      - generate_summary
    depends_on:
    - annotation
  all:
    summary: all
    requires:
    - ../workflow_candidates/chandanbfx__scRNA-seq-Seurat-Workflow/config/config.yaml
    snakemake:
      snakefile: ../workflow_candidates/chandanbfx__scRNA-seq-Seurat-Workflow/Snakefile
      directory: ../workflow_candidates/chandanbfx__scRNA-seq-Seurat-Workflow
      use_conda: true
      cores: '{source_cores}'
      scheduler: greedy
      configfile: ../workflow_candidates/chandanbfx__scRNA-seq-Seurat-Workflow/config/config.yaml
      targets:
      - all
    depends_on:
    - generate_summary
