$schema: "https://json-schema.org/draft/2020-12/schema"

description: read-alignment-pangenome workflow configuration

type: object

properties:
  samples:
    type: string

  units:
    type: string

  ref:
    type: object
    properties:
      n_chromosomes:
        type: integer
      species:
        type: string
      release:
        type: integer
      build:
        type: string
      pangenome:
        type: object
        properties:
          activate:
            type: boolean
          source:
            type: string
          version:
            type: string
        required:
          - activate
          - source
          - version
    required:
      - species
      - release
      - build
      - pangenome

  primers:
    type: object
    properties:
      trimming:
        type: object
        properties:
          activate:
            type: boolean
          primers_fa1:
            type: string
          primers_fa2:
            type: string
          tsv:
            type: string
          library_error:
            type: integer
          library_length:
            type: integer
    required:
      - trimming

  remove_duplicates:
    type: object
    properties:
      activate:
        type: boolean
    required:
      - activate

  calc_consensus_reads:
    type: object
    properties:
      activate:
        type: boolean
    required:
      - activate

  params:
    type: object
    properties:
      fastp:
        type: string
      gatk:
        type: object
        properties:
          BaseRecalibrator:
            type: string
          applyBQSR:
            type: string
        required:
          - BaseRecalibrator
          - applyBQSR
      picard:
        type: object
        properties:
          MarkDuplicates:
            type: string
        required:
          - MarkDuplicates
    required:
      - fastp
      - gatk
      - picard

required:
  - samples
  - units
  - ref
  - primers
  - remove_duplicates
  - calc_consensus_reads
  - params
