# sample setup and configuration according to the dataset linked here:
# https://www.10xgenomics.com/support/software/cell-ranger/latest/analysis/running-pipelines/cr-5p-multi#all-libs
# Note: the actual data does not seem to contain any CRISPR Guide Capture data,
# so this is omitted in the sample sheet here.

pool_sheet: "config/pools.gex_vdj_antibody.tsv"

multi_config_csv_sections:
  gene-expression:
    reference: "resources/refdata/"
    create-bam: "true"
    tenx-cloud-token-path: ""
    cell-annotation-model: ""
    expect-cells: "10000"

  multiplexing:
    activate: false

  vdj:
    reference: "resources/refdata/"
    r1-length: ""
    r2-length: ""

  feature:
    # Feature reference csv downloaded from:
    # https://cf.10xgenomics.com/samples/cell-vdj/5.0.0/sc5p_v2_hs_PBMC_10k_multi_5gex_5fb_b_t/sc5p_v2_hs_PBMC_10k_multi_5gex_5fb_b_t_feature_ref.csv
    reference: "config/feature_ref.gex_vdj_antibody.csv"
    min-cripsr-umi: ""
