# Test case setup inspired by:
# https://www.10xgenomics.com/support/software/cell-ranger/latest/analysis/running-pipelines/cr-5p-antigen#tcr

pool_sheet: "config/pools.tcr_multiplex.tsv"

multi_config_csv_sections:
  gene-expression:
    reference: "resources/refdata/"
    create-bam: "true"
    expect-cells: ""

  vdj:
    reference: "resources/refdata/"
    inner-enrichment-primers: ""

  feature:
    # Feature reference file downloaded from:
    # https://www.10xgenomics.com/support/software/cell-ranger/latest/analysis/running-pipelines/cr-5p-antigen#feature-ref-tcr-example
    reference: "config/feature_ref.tcr_multiplex.csv"
    r1-length: ""
    r2-length: ""

  multiplexing:
    activate: true
    tsv: "config/multiplexing.tcr_multiplex.tsv"
