workflow_id: cite-seq-alevin-fry-seurat-finish
source_cores: 8
steps:
  get_sra:
    summary: get_sra
    requires:
    - ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/config/config.yaml
    snakemake:
      snakefile: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/workflow/Snakefile
      directory: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat
      use_conda: true
      cores: '{source_cores}'
      scheduler: greedy
      configfile: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/config/config.yaml
      root_target: all
      until:
      - get_sra
  get_genome:
    summary: get_genome
    requires:
    - ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/config/config.yaml
    snakemake:
      snakefile: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/workflow/Snakefile
      directory: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat
      use_conda: true
      cores: '{source_cores}'
      scheduler: greedy
      configfile: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/config/config.yaml
      root_target: all
      until:
      - get_genome
    depends_on:
    - get_sra
  get_annotation:
    summary: get_annotation
    requires:
    - ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/config/config.yaml
    snakemake:
      snakefile: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/workflow/Snakefile
      directory: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat
      use_conda: true
      cores: '{source_cores}'
      scheduler: greedy
      configfile: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/config/config.yaml
      root_target: all
      until:
      - get_annotation
    depends_on:
    - get_genome
  get_geneid2name:
    summary: get_geneid2name
    requires:
    - ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/config/config.yaml
    snakemake:
      snakefile: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/workflow/Snakefile
      directory: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat
      use_conda: true
      cores: '{source_cores}'
      scheduler: greedy
      configfile: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/config/config.yaml
      root_target: all
      until:
      - get_geneid2name
    depends_on:
    - get_annotation
  build_splici_transcriptome:
    summary: build_splici_transcriptome
    requires:
    - ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/config/config.yaml
    snakemake:
      snakefile: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/workflow/Snakefile
      directory: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat
      use_conda: true
      cores: '{source_cores}'
      scheduler: greedy
      configfile: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/config/config.yaml
      root_target: all
      until:
      - build_splici_transcriptome
    depends_on:
    - get_geneid2name
  spoof_t2g:
    summary: spoof_t2g
    requires:
    - ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/config/config.yaml
    snakemake:
      snakefile: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/workflow/Snakefile
      directory: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat
      use_conda: true
      cores: '{source_cores}'
      scheduler: greedy
      configfile: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/config/config.yaml
      root_target: all
      until:
      - spoof_t2g
    depends_on:
    - build_splici_transcriptome
  salmon_index:
    summary: salmon_index
    requires:
    - ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/config/config.yaml
    snakemake:
      snakefile: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/workflow/Snakefile
      directory: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat
      use_conda: true
      cores: '{source_cores}'
      scheduler: greedy
      configfile: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/config/config.yaml
      root_target: all
      until:
      - salmon_index
    depends_on:
    - spoof_t2g
  salmon_alevin:
    summary: salmon_alevin
    requires:
    - ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/config/config.yaml
    snakemake:
      snakefile: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/workflow/Snakefile
      directory: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat
      use_conda: true
      cores: '{source_cores}'
      scheduler: greedy
      configfile: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/config/config.yaml
      root_target: all
      until:
      - salmon_alevin
    depends_on:
    - salmon_index
  alevin_fry_preprocess:
    summary: alevin_fry_preprocess
    requires:
    - ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/config/config.yaml
    snakemake:
      snakefile: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/workflow/Snakefile
      directory: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat
      use_conda: true
      cores: '{source_cores}'
      scheduler: greedy
      configfile: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/config/config.yaml
      root_target: all
      until:
      - alevin_fry_preprocess
    depends_on:
    - salmon_alevin
  alevin_fry_quant:
    summary: alevin_fry_quant
    requires:
    - ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/config/config.yaml
    snakemake:
      snakefile: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/workflow/Snakefile
      directory: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat
      use_conda: true
      cores: '{source_cores}'
      scheduler: greedy
      configfile: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/config/config.yaml
      root_target: all
      until:
      - alevin_fry_quant
    depends_on:
    - alevin_fry_preprocess
  seurat:
    summary: seurat
    requires:
    - ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/config/config.yaml
    snakemake:
      snakefile: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/workflow/Snakefile
      directory: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat
      use_conda: true
      cores: '{source_cores}'
      scheduler: greedy
      configfile: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/config/config.yaml
      root_target: all
      until:
      - seurat
    depends_on:
    - alevin_fry_quant
  plot_initial_hto_counts:
    summary: plot_initial_hto_counts
    requires:
    - ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/config/config.yaml
    snakemake:
      snakefile: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/workflow/Snakefile
      directory: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat
      use_conda: true
      cores: '{source_cores}'
      scheduler: greedy
      configfile: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/config/config.yaml
      root_target: all
      until:
      - plot_initial_hto_counts
    depends_on:
    - seurat
  filter_normalize_demux:
    summary: filter_normalize_demux
    requires:
    - ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/config/config.yaml
    snakemake:
      snakefile: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/workflow/Snakefile
      directory: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat
      use_conda: true
      cores: '{source_cores}'
      scheduler: greedy
      configfile: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/config/config.yaml
      root_target: all
      until:
      - filter_normalize_demux
    depends_on:
    - plot_initial_hto_counts
  plot_counts_hto_filtered:
    summary: plot_counts_hto_filtered
    requires:
    - ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/config/config.yaml
    snakemake:
      snakefile: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/workflow/Snakefile
      directory: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat
      use_conda: true
      cores: '{source_cores}'
      scheduler: greedy
      configfile: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/config/config.yaml
      root_target: all
      until:
      - plot_counts_hto_filtered
    depends_on:
    - filter_normalize_demux
  filter_negatives:
    summary: filter_negatives
    requires:
    - ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/config/config.yaml
    snakemake:
      snakefile: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/workflow/Snakefile
      directory: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat
      use_conda: true
      cores: '{source_cores}'
      scheduler: greedy
      configfile: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/config/config.yaml
      root_target: all
      until:
      - filter_negatives
    depends_on:
    - plot_counts_hto_filtered
  plot_umap_singlets_doublets:
    summary: plot_umap_singlets_doublets
    requires:
    - ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/config/config.yaml
    snakemake:
      snakefile: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/workflow/Snakefile
      directory: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat
      use_conda: true
      cores: '{source_cores}'
      scheduler: greedy
      configfile: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/config/config.yaml
      root_target: all
      until:
      - plot_umap_singlets_doublets
    depends_on:
    - filter_negatives
  filter_to_singlets:
    summary: filter_to_singlets
    requires:
    - ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/config/config.yaml
    snakemake:
      snakefile: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/workflow/Snakefile
      directory: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat
      use_conda: true
      cores: '{source_cores}'
      scheduler: greedy
      configfile: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/config/config.yaml
      root_target: all
      until:
      - filter_to_singlets
    depends_on:
    - plot_umap_singlets_doublets
  all:
    summary: all
    requires:
    - ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/config/config.yaml
    snakemake:
      snakefile: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/workflow/Snakefile
      directory: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat
      use_conda: true
      cores: '{source_cores}'
      scheduler: greedy
      configfile: ../workflow_candidates/snakemake-workflows__cite-seq-alevin-fry-seurat/config/config.yaml
      targets:
      - all
    depends_on:
    - filter_to_singlets
