# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.


# load configuration
# -----------------------------------------------------
configfile: "config/config.yaml"


# load rules
# -----------------------------------------------------
include: "rules/common.smk"
include: "rules/ref.smk"
include: "rules/mapping.smk"
include: "rules/fusion_calling.smk"


# target rules
# -----------------------------------------------------
rule all:
    input:
        final_output,
    default_target: True
