# profiles/slurm/config.yaml
executor: slurm
jobs: 16
use-conda: true
conda-frontend: conda
latency-wait: 60
keep-going: true
max-jobs-per-second: 2
max-status-checks-per-second: 5

sbatch:
  job-name: "smk-{rule}-{jobid}"
  cpus-per-task: "{threads}"
  mem: "{resources.mem_mb}"
  tmp: "{resources.tmp_mb}"
  qos: "{resources.qos}"