workflow_id: epigen-dea_seurat-finish
source_cores: 8
steps:
  dea:
    summary: dea
    requires:
    - ../workflow_candidates/epigen__dea_seurat/config/config.yaml
    snakemake:
      snakefile: ../workflow_candidates/epigen__dea_seurat/workflow/Snakefile
      directory: ../workflow_candidates/epigen__dea_seurat
      use_conda: true
      cores: '{source_cores}'
      scheduler: greedy
      configfile: ../workflow_candidates/epigen__dea_seurat/config/config.yaml
      root_target: all
      until:
      - dea
  aggregate:
    summary: aggregate
    requires:
    - ../workflow_candidates/epigen__dea_seurat/config/config.yaml
    snakemake:
      snakefile: ../workflow_candidates/epigen__dea_seurat/workflow/Snakefile
      directory: ../workflow_candidates/epigen__dea_seurat
      use_conda: true
      cores: '{source_cores}'
      scheduler: greedy
      configfile: ../workflow_candidates/epigen__dea_seurat/config/config.yaml
      root_target: all
      until:
      - aggregate
    depends_on:
    - dea
  feature_lists:
    summary: feature_lists
    requires:
    - ../workflow_candidates/epigen__dea_seurat/config/config.yaml
    snakemake:
      snakefile: ../workflow_candidates/epigen__dea_seurat/workflow/Snakefile
      directory: ../workflow_candidates/epigen__dea_seurat
      use_conda: true
      cores: '{source_cores}'
      scheduler: greedy
      configfile: ../workflow_candidates/epigen__dea_seurat/config/config.yaml
      root_target: all
      until:
      - feature_lists
    depends_on:
    - aggregate
  volcanos:
    summary: volcanos
    requires:
    - ../workflow_candidates/epigen__dea_seurat/config/config.yaml
    snakemake:
      snakefile: ../workflow_candidates/epigen__dea_seurat/workflow/Snakefile
      directory: ../workflow_candidates/epigen__dea_seurat
      use_conda: true
      cores: '{source_cores}'
      scheduler: greedy
      configfile: ../workflow_candidates/epigen__dea_seurat/config/config.yaml
      root_target: all
      until:
      - volcanos
    depends_on:
    - feature_lists
  heatmap:
    summary: heatmap
    requires:
    - ../workflow_candidates/epigen__dea_seurat/config/config.yaml
    snakemake:
      snakefile: ../workflow_candidates/epigen__dea_seurat/workflow/Snakefile
      directory: ../workflow_candidates/epigen__dea_seurat
      use_conda: true
      cores: '{source_cores}'
      scheduler: greedy
      configfile: ../workflow_candidates/epigen__dea_seurat/config/config.yaml
      root_target: all
      until:
      - heatmap
    depends_on:
    - volcanos
  env_export:
    summary: env_export
    requires:
    - ../workflow_candidates/epigen__dea_seurat/config/config.yaml
    snakemake:
      snakefile: ../workflow_candidates/epigen__dea_seurat/workflow/Snakefile
      directory: ../workflow_candidates/epigen__dea_seurat
      use_conda: true
      cores: '{source_cores}'
      scheduler: greedy
      configfile: ../workflow_candidates/epigen__dea_seurat/config/config.yaml
      root_target: all
      until:
      - env_export
    depends_on:
    - heatmap
  config_export:
    summary: config_export
    requires:
    - ../workflow_candidates/epigen__dea_seurat/config/config.yaml
    snakemake:
      snakefile: ../workflow_candidates/epigen__dea_seurat/workflow/Snakefile
      directory: ../workflow_candidates/epigen__dea_seurat
      use_conda: true
      cores: '{source_cores}'
      scheduler: greedy
      configfile: ../workflow_candidates/epigen__dea_seurat/config/config.yaml
      root_target: all
      until:
      - config_export
    depends_on:
    - env_export
  annot_export:
    summary: annot_export
    requires:
    - ../workflow_candidates/epigen__dea_seurat/config/config.yaml
    snakemake:
      snakefile: ../workflow_candidates/epigen__dea_seurat/workflow/Snakefile
      directory: ../workflow_candidates/epigen__dea_seurat
      use_conda: true
      cores: '{source_cores}'
      scheduler: greedy
      configfile: ../workflow_candidates/epigen__dea_seurat/config/config.yaml
      root_target: all
      until:
      - annot_export
    depends_on:
    - config_export
  feature_list_export:
    summary: feature_list_export
    requires:
    - ../workflow_candidates/epigen__dea_seurat/config/config.yaml
    snakemake:
      snakefile: ../workflow_candidates/epigen__dea_seurat/workflow/Snakefile
      directory: ../workflow_candidates/epigen__dea_seurat
      use_conda: true
      cores: '{source_cores}'
      scheduler: greedy
      configfile: ../workflow_candidates/epigen__dea_seurat/config/config.yaml
      root_target: all
      until:
      - feature_list_export
    depends_on:
    - annot_export
  all:
    summary: all
    requires:
    - ../workflow_candidates/epigen__dea_seurat/config/config.yaml
    snakemake:
      snakefile: ../workflow_candidates/epigen__dea_seurat/workflow/Snakefile
      directory: ../workflow_candidates/epigen__dea_seurat
      use_conda: true
      cores: '{source_cores}'
      scheduler: greedy
      configfile: ../workflow_candidates/epigen__dea_seurat/config/config.yaml
      targets:
      - all
    depends_on:
    - feature_list_export
